site_name: 'Andy M. Newhouse'
personality: formal
show_signup: false
social:
  -
    name: Email
    url: 'mailto:hi@andymnewhouse.me'
    icon: site/social-icons/email.svg
  -
    name: Twitter
    url: 'https://twitter.com/techenby'
    icon: site/social-icons/twitter.svg
  -
    name: Github
    url: 'https://github.com/techenby'
    icon: site/social-icons/github.svg
