title: Relationship
updated_by: 036389ec-e4c8-4f9d-86ba-21d98c3226b1
updated_at: 1638469375
blueprint: category
hero_image: nn-blog/cas-us-in-greenhouse.jpg
icon: icons/relationship.svg
gradient: 'from-rose-500 to-rose-700'
