title: Vacation
updated_by: 036389ec-e4c8-4f9d-86ba-21d98c3226b1
updated_at: 1638469395
blueprint: category
hero_image: nn-blog/cas-reef.jpg
icon: icons/vacation.svg
gradient: 'from-yellow-500 to-yellow-700'
