title: Wedding
updated_by: 036389ec-e4c8-4f9d-86ba-21d98c3226b1
updated_at: 1638469428
blueprint: category
hero_image: nn-wedding/DSC04880.jpg
icon: icons/wedding.svg
gradient: 'from-emerald-500 to-emerald-700'
